// Document Generation Functions with Signova Demo Watermark

const WATERMARK = `
═══════════════════════════════════════════════════════════════════════════════
                              ★ SIGNOVA DEMO ★
        This is a preview document. Subscribe to remove watermark and
        access full editing, e-signature, and download capabilities.
═══════════════════════════════════════════════════════════════════════════════
`;

const FOOTER_WATERMARK = `
---
★ SIGNOVA DEMO - Preview Only ★
Generated by Signova AI - Professional Document Generation Platform
Subscribe now to download, edit, and electronically sign this document.
Visit: https://signova.ai/pricing
`;

export const generateNDA = (data: any): string => {
  const infoTypesText = (data.infoTypes || []).map((type: string) => {
    const labels: Record<string, string> = {
      business: 'business strategies and plans',
      financial: 'financial information',
      technical: 'technical data and trade secrets',
      customer: 'customer/client information',
      product: 'product designs and specifications'
    };
    return labels[type] || type;
  }).join(', ') || 'confidential business information';

  const purposeText: Record<string, string> = {
    partnership: 'exploring a potential business partnership',
    employment: 'employment or contractor relationship',
    acquisition: 'discussing a potential sale or acquisition',
    investment: 'evaluating an investment opportunity',
    other: 'business purposes'
  };

  const durationText = data.duration === 'indefinite' 
    ? 'indefinitely' 
    : `for a period of ${data.duration} year${data.duration === '1' ? '' : 's'}`;

  const returnText: Record<string, string> = {
    'upon-request': 'upon written request by the Disclosing Party',
    'upon-termination': 'upon termination of this Agreement',
    'not-required': "at the Receiving Party's discretion"
  };

  return `${WATERMARK}

NON-DISCLOSURE AGREEMENT

This Non-Disclosure Agreement ("Agreement") is entered into as of ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} by and between:

DISCLOSING PARTY: ${data.disclosingParty || '[DISCLOSING PARTY]'}
RECEIVING PARTY: ${data.receivingParty || '[RECEIVING PARTY]'}

${data.isMutual ? 'This is a MUTUAL Non-Disclosure Agreement where both parties may disclose and receive confidential information.\n' : ''}
1. PURPOSE
The parties wish to explore ${purposeText[data.purpose] || 'a business relationship'} and in connection with this purpose, it may be necessary for the Disclosing Party to disclose certain confidential and proprietary information to the Receiving Party.

2. CONFIDENTIAL INFORMATION
For purposes of this Agreement, "Confidential Information" includes, but is not limited to: ${infoTypesText}.

3. OBLIGATIONS OF RECEIVING PARTY
The Receiving Party agrees to:
a) Hold and maintain the Confidential Information in strict confidence
b) Not disclose the Confidential Information to any third parties without prior written consent
c) Use the Confidential Information solely for the purpose stated above
d) Protect the Confidential Information with the same degree of care used to protect its own confidential information

4. TERM
The obligations of confidentiality shall remain in effect ${durationText} from the date of disclosure of the Confidential Information.

5. RETURN OF MATERIALS
Upon termination of discussions or ${returnText[data.returnMaterials] || 'upon request'}, the Receiving Party shall return or destroy all Confidential Information and any copies thereof.

6. GOVERNING LAW
This Agreement shall be governed by and construed in accordance with the laws of the State of ${data.jurisdiction || '[STATE]'}, without regard to its conflict of law provisions.

7. ENTIRE AGREEMENT
This Agreement constitutes the entire agreement between the parties concerning the subject matter hereof and supersedes all prior agreements and understandings.

IN WITNESS WHEREOF, the parties have executed this Agreement as of the date first written above.

_________________________________
${data.disclosingParty || '[DISCLOSING PARTY]'}
Signature

Date: _________________


_________________________________
${data.receivingParty || '[RECEIVING PARTY]'}
Signature

Date: _________________

${FOOTER_WATERMARK}`;
};

export const generateCommercialLease = (data: any): string => {
  return `${WATERMARK}

COMMERCIAL LEASE AGREEMENT

This Commercial Lease Agreement ("Lease") is entered into as of ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} by and between:

LANDLORD: ${data.landlordName || '[LANDLORD NAME]'}
TENANT: ${data.tenantName || '[TENANT NAME]'}

1. PREMISES
Landlord hereby leases to Tenant the following commercial property:
Address: ${data.propertyAddress || '[PROPERTY ADDRESS]'}
Property Type: ${data.propertyType || '[PROPERTY TYPE]'}
Square Footage: ${data.squareFootage || '[SQUARE FOOTAGE]'}

2. PERMITTED USE
The Premises shall be used solely for the operation of: ${data.tenantBusinessType || '[BUSINESS TYPE]'}

3. TERM
The initial lease term shall be ${data.leaseTerm || '[LEASE TERM]'} year(s), commencing on _________________ and ending on _________________.

4. RENT
Base Monthly Rent: ${data.monthlyRent || '[MONTHLY RENT]'}
Rent is due on the first day of each month.
Late Fee: 5% of monthly rent if paid after the 5th day of the month.

5. SECURITY DEPOSIT
Tenant shall pay a security deposit of ${data.securityDeposit || '[SECURITY DEPOSIT]'} upon execution of this Lease.
The security deposit shall be returned within 30 days of lease termination, less any deductions for damages or unpaid rent.

6. UTILITIES AND SERVICES
Tenant shall be responsible for all utilities including electricity, gas, water, internet, and telephone services.

7. MAINTENANCE AND REPAIRS
Landlord: Responsible for structural repairs, roof, exterior walls, and common areas.
Tenant: Responsible for interior maintenance, HVAC filters, and minor repairs under $500.

8. INSURANCE
Tenant shall maintain commercial general liability insurance with minimum coverage of $1,000,000 per occurrence.
Tenant shall name Landlord as additional insured on all policies.

9. ALTERATIONS
Tenant shall not make any alterations, additions, or improvements without Landlord's prior written consent.

10. DEFAULT AND REMEDIES
If Tenant fails to pay rent within 10 days of due date or breaches any term of this Lease, Landlord may:
a) Terminate this Lease with 30 days written notice
b) Pursue legal remedies for unpaid rent and damages

11. GOVERNING LAW
This Lease shall be governed by the laws of the State of ${data.jurisdiction || '[STATE]'}.

IN WITNESS WHEREOF, the parties have executed this Lease as of the date first written above.

_________________________________
LANDLORD: ${data.landlordName || '[LANDLORD NAME]'}
Signature

Date: _________________


_________________________________
TENANT: ${data.tenantName || '[TENANT NAME]'}
Signature

Date: _________________

${FOOTER_WATERMARK}`;
};

export const generateEmployeeHandbook = (data: any): string => {
  const workArrangementText: Record<string, string> = {
    'onsite': 'All employees are expected to work from our office location during regular business hours.',
    'remote': 'We are a fully remote company. Employees may work from any location with reliable internet access.',
    'hybrid': 'We offer a hybrid work arrangement. Employees are expected to be in the office [X] days per week.'
  };

  const ptoText: Record<string, string> = {
    'unlimited': 'We offer unlimited paid time off. We trust our employees to manage their time responsibly while meeting their work obligations.',
    '15days': 'Full-time employees receive 15 days of paid time off per year, accrued monthly.',
    '20days': 'Full-time employees receive 20 days of paid time off per year, accrued monthly.',
    'accrual': 'PTO is accrued based on length of service. New employees accrue 1.25 days per month.'
  };

  const dressCodeText: Record<string, string> = {
    'formal': 'Business formal attire is required. This includes suits, dress shirts, ties, and professional footwear.',
    'business-casual': 'Business casual attire is expected. Jeans are acceptable on Fridays.',
    'casual': 'Casual attire is acceptable. Please use good judgment and dress appropriately for meetings.',
    'none': 'There is no formal dress code. We trust employees to dress appropriately for their work environment.'
  };

  return `${WATERMARK}

${data.companyName || '[COMPANY NAME]'}
EMPLOYEE HANDBOOK

Effective Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

═══════════════════════════════════════════════════════════════════════════════

TABLE OF CONTENTS
1. Welcome & Company Overview
2. Employment Policies
3. Work Arrangements
4. Time Off & Leave
5. Compensation & Benefits
6. Code of Conduct
7. Health & Safety
8. Acknowledgment

═══════════════════════════════════════════════════════════════════════════════

1. WELCOME & COMPANY OVERVIEW

Welcome to ${data.companyName || '[COMPANY NAME]'}!

We are excited to have you join our team. This handbook outlines our policies, procedures, and expectations to help you succeed in your role.

Industry: ${data.industry || '[INDUSTRY]'}
Company Size: ${data.employeeCount || '[EMPLOYEE COUNT]'} employees

Our Mission: To deliver exceptional value to our customers while fostering a positive and inclusive workplace.

═══════════════════════════════════════════════════════════════════════════════

2. EMPLOYMENT POLICIES

Equal Employment Opportunity
${data.companyName || '[COMPANY NAME]'} is an equal opportunity employer. We do not discriminate based on race, color, religion, sex, national origin, age, disability, veteran status, sexual orientation, gender identity, or any other protected characteristic.

At-Will Employment
Employment with ${data.companyName || '[COMPANY NAME]'} is at-will, meaning either party may terminate the employment relationship at any time, with or without cause or notice.

═══════════════════════════════════════════════════════════════════════════════

3. WORK ARRANGEMENTS

${workArrangementText[data.workArrangement] || 'Work arrangement details to be determined.'}

Standard Work Hours: 9:00 AM - 5:00 PM, Monday through Friday
Core Hours (for flexible schedules): 10:00 AM - 3:00 PM

═══════════════════════════════════════════════════════════════════════════════

4. TIME OFF & LEAVE

Paid Time Off (PTO)
${ptoText[data.ptoPolicy] || 'PTO policy details to be determined.'}

Holidays
The company observes the following paid holidays:
• New Year's Day
• Martin Luther King Jr. Day
• Presidents' Day
• Memorial Day
• Independence Day
• Labor Day
• Thanksgiving Day
• Day after Thanksgiving
• Christmas Eve
• Christmas Day

Sick Leave
Employees may use PTO for sick days or may be eligible for additional sick leave as required by state law.

═══════════════════════════════════════════════════════════════════════════════

5. COMPENSATION & BENEFITS

Pay Schedule: Bi-weekly (every other Friday)

Benefits Offered:
${data.healthInsurance ? '✓ Health Insurance (Medical, Dental, Vision)' : '○ Health Insurance - Not currently offered'}
${data['401k'] ? '✓ 401(k) Retirement Plan with company match' : '○ 401(k) - Not currently offered'}
${data.stockOptions ? '✓ Stock Options/Equity participation' : '○ Stock Options - Not currently offered'}

═══════════════════════════════════════════════════════════════════════════════

6. CODE OF CONDUCT

Dress Code
${dressCodeText[data.dressCode] || 'Dress code policy to be determined.'}

Professional Behavior
All employees are expected to:
• Treat colleagues, customers, and partners with respect
• Maintain confidentiality of company information
• Avoid conflicts of interest
• Report any concerns through appropriate channels

═══════════════════════════════════════════════════════════════════════════════

7. HEALTH & SAFETY

${data.companyName || '[COMPANY NAME]'} is committed to providing a safe and healthy work environment. All employees are expected to follow safety guidelines and report any hazards immediately.

In compliance with ${data.jurisdiction || '[STATE]'} law, we maintain all required workplace safety standards.

═══════════════════════════════════════════════════════════════════════════════

8. ACKNOWLEDGMENT

I acknowledge that I have received and read the ${data.companyName || '[COMPANY NAME]'} Employee Handbook. I understand that the policies described herein are subject to change and that I am responsible for staying informed of any updates.

Employee Name: _________________________________

Employee Signature: _________________________________

Date: _________________________________

${FOOTER_WATERMARK}`;
};

export const generatePartnershipDissolution = (data: any): string => {
  const dissolutionReasonText: Record<string, string> = {
    'mutual': 'by mutual agreement of all partners',
    'retirement': 'due to the retirement of one or more partners',
    'dispute': 'due to irreconcilable differences between partners',
    'business-closure': 'due to the decision to close the business',
    'other': 'for reasons agreed upon by the partners'
  };

  const assetDivisionText: Record<string, string> = {
    'ownership': 'in proportion to each partner\\'s ownership percentage',
    'equal': 'equally among all partners',
    'negotiated': 'according to the terms negotiated and specified in this agreement'
  };

  return `${WATERMARK}

PARTNERSHIP DISSOLUTION AGREEMENT

This Partnership Dissolution Agreement ("Agreement") is entered into as of ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} by and between the undersigned partners.

═══════════════════════════════════════════════════════════════════════════════

1. PARTNERSHIP INFORMATION

Partnership Name: ${data.partnershipName || '[PARTNERSHIP NAME]'}
Date of Formation: ${data.formationDate || '[FORMATION DATE]'}
Type of Business: ${data.businessType || '[BUSINESS TYPE]'}

═══════════════════════════════════════════════════════════════════════════════

2. PARTNERS

Partner 1:
Name: ${data.partner1Name || '[PARTNER 1 NAME]'}
Ownership Percentage: ${data.partner1Ownership || '[OWNERSHIP %]'}

Partner 2:
Name: ${data.partner2Name || '[PARTNER 2 NAME]'}
Ownership Percentage: ${data.partner2Ownership || '[OWNERSHIP %]'}

═══════════════════════════════════════════════════════════════════════════════

3. REASON FOR DISSOLUTION

The partners have agreed to dissolve the partnership ${dissolutionReasonText[data.dissolutionReason] || 'for reasons agreed upon by the partners'}.

═══════════════════════════════════════════════════════════════════════════════

4. EFFECTIVE DATE

The dissolution shall be effective as of _________________ ("Effective Date").

═══════════════════════════════════════════════════════════════════════════════

5. DIVISION OF ASSETS

All partnership assets shall be divided ${assetDivisionText[data.assetDivision] || 'as agreed upon by the partners'}.

Assets to be divided include but are not limited to:
• Cash and bank accounts
• Accounts receivable
• Equipment and inventory
• Real property (if any)
• Intellectual property
• Goodwill

═══════════════════════════════════════════════════════════════════════════════

6. ALLOCATION OF LIABILITIES

All partnership debts and liabilities shall be paid from partnership assets before any distribution to partners. Any remaining liabilities shall be allocated ${assetDivisionText[data.assetDivision] || 'as agreed upon by the partners'}.

═══════════════════════════════════════════════════════════════════════════════

7. WINDING UP PROCEDURES

The partners agree to:
a) Complete all pending business transactions
b) Collect all accounts receivable
c) Pay all outstanding debts and obligations
d) File all necessary tax returns
e) Cancel all business licenses and permits
f) Notify all customers, vendors, and creditors of the dissolution

═══════════════════════════════════════════════════════════════════════════════

8. NON-COMPETITION

[Optional: Include if applicable]
For a period of _____ years following the Effective Date, no partner shall engage in a competing business within _____ miles of the partnership's primary location.

═══════════════════════════════════════════════════════════════════════════════

9. CONFIDENTIALITY

All partners agree to maintain the confidentiality of partnership business information and trade secrets indefinitely.

═══════════════════════════════════════════════════════════════════════════════

10. RELEASE OF CLAIMS

Each partner hereby releases and forever discharges the other partners from any and all claims, demands, and causes of action arising out of the partnership, except as specifically provided in this Agreement.

═══════════════════════════════════════════════════════════════════════════════

11. GOVERNING LAW

This Agreement shall be governed by and construed in accordance with the laws of the State of ${data.jurisdiction || '[STATE]'}.

═══════════════════════════════════════════════════════════════════════════════

12. SIGNATURES

IN WITNESS WHEREOF, the partners have executed this Agreement as of the date first written above.


_________________________________
${data.partner1Name || '[PARTNER 1 NAME]'}
Signature

Date: _________________


_________________________________
${data.partner2Name || '[PARTNER 2 NAME]'}
Signature

Date: _________________

${FOOTER_WATERMARK}`;
};

export const generateFreelanceContract = (data: any): string => {
  const paymentTypeText: Record<string, string> = {
    'hourly': `at an hourly rate of ${data.rate || '[RATE]'}`,
    'fixed': `a fixed project fee of ${data.rate || '[AMOUNT]'}`,
    'retainer': `a monthly retainer of ${data.rate || '[AMOUNT]'}`,
    'milestone': `based on milestones, totaling ${data.rate || '[AMOUNT]'}`
  };

  const paymentTermsText: Record<string, string> = {
    'upfront': '100% payment is due upon execution of this Agreement',
    '50-50': '50% is due upon execution, and 50% upon project completion',
    'net30': 'Payment is due within 30 days of invoice date',
    'milestone': 'Payment is due upon completion of each milestone'
  };

  return `${WATERMARK}

FREELANCE CONSULTING AGREEMENT

This Freelance Consulting Agreement ("Agreement") is entered into as of ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} by and between:

CLIENT: ${data.clientName || '[CLIENT NAME]'}
CONSULTANT: ${data.consultantName || '[CONSULTANT NAME]'}

═══════════════════════════════════════════════════════════════════════════════

1. ENGAGEMENT

Client hereby engages Consultant to provide ${data.consultantType || '[SERVICE TYPE]'} services as an independent contractor, and Consultant hereby accepts such engagement, subject to the terms and conditions of this Agreement.

═══════════════════════════════════════════════════════════════════════════════

2. SCOPE OF SERVICES

Project Description:
${data.projectDescription || '[PROJECT DESCRIPTION]'}

Key Deliverables:
${data.deliverables || '[DELIVERABLES]'}

═══════════════════════════════════════════════════════════════════════════════

3. TERM

This Agreement shall commence on the date first written above and shall continue for ${data.timeline || '[PROJECT TIMELINE]'}, unless earlier terminated in accordance with Section 9.

═══════════════════════════════════════════════════════════════════════════════

4. COMPENSATION

Consultant shall be compensated ${paymentTypeText[data.paymentType] || 'as agreed upon by the parties'}.

Payment Terms:
${paymentTermsText[data.paymentTerms] || 'Payment terms to be determined.'}

Expenses:
Pre-approved expenses will be reimbursed within 30 days of submission with receipts.

═══════════════════════════════════════════════════════════════════════════════

5. INDEPENDENT CONTRACTOR STATUS

Consultant is an independent contractor and not an employee of Client. Consultant shall be solely responsible for:
• Payment of all taxes
• Obtaining any required business licenses
• Providing own equipment and workspace
• Maintaining appropriate insurance

═══════════════════════════════════════════════════════════════════════════════

6. INTELLECTUAL PROPERTY

Work Product: All work product created by Consultant in the performance of this Agreement shall be considered "work made for hire" and shall be the sole property of Client.

Pre-Existing Materials: Consultant retains ownership of any pre-existing materials, tools, or methodologies used in the project.

═══════════════════════════════════════════════════════════════════════════════

7. CONFIDENTIALITY

Consultant agrees to maintain the confidentiality of all Client information and shall not disclose such information to any third party without Client's prior written consent.

═══════════════════════════════════════════════════════════════════════════════

8. NON-SOLICITATION

During the term of this Agreement and for a period of one (1) year thereafter, Consultant shall not directly solicit any employees or clients of Client.

═══════════════════════════════════════════════════════════════════════════════

9. TERMINATION

Either party may terminate this Agreement:
• With 14 days written notice for any reason
• Immediately for material breach

Upon termination:
• Client shall pay for all work completed to date
• Consultant shall deliver all completed work product

═══════════════════════════════════════════════════════════════════════════════

10. LIMITATION OF LIABILITY

Consultant's total liability under this Agreement shall not exceed the total compensation paid under this Agreement.

═══════════════════════════════════════════════════════════════════════════════

11. GOVERNING LAW

This Agreement shall be governed by and construed in accordance with the laws of the State of ${data.jurisdiction || '[STATE]'}.

═══════════════════════════════════════════════════════════════════════════════

12. ENTIRE AGREEMENT

This Agreement constitutes the entire agreement between the parties and supersedes all prior negotiations, representations, or agreements relating to the subject matter hereof.

═══════════════════════════════════════════════════════════════════════════════

IN WITNESS WHEREOF, the parties have executed this Agreement as of the date first written above.


_________________________________
CLIENT: ${data.clientName || '[CLIENT NAME]'}
Signature

Date: _________________


_________________________________
CONSULTANT: ${data.consultantName || '[CONSULTANT NAME]'}
Signature

Date: _________________

${FOOTER_WATERMARK}`;
};

// Export all generators
export const documentGenerators: Record<string, (data: any) => string> = {
  'nda': generateNDA,
  'commercial-lease': generateCommercialLease,
  'employee-handbook': generateEmployeeHandbook,
  'partnership-dissolution': generatePartnershipDissolution,
  'freelance-contract': generateFreelanceContract
};
