import React, { useState } from 'react';

// SEO: AI-Powered Document Signing Software
// Generated by Signova Programmatic SEO Engine

export default function AIDocumentSigning() {
  const [email, setEmail] = useState('');
  const [submitted, setSubmitted] = useState(false);

  const handleCapture = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await fetch('/api/intent-capture', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, source: 'ai-document-signing', competitor: 'traditional e-signature tools' })
      });
    } catch {}
    setSubmitted(true);
  };

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <div className="mb-4 inline-block bg-green-50 text-green-700 text-sm font-medium px-3 py-1 rounded-full">
          Save up to 67% vs traditional e-signature tools
        </div>
        <h1 className="text-4xl font-bold text-slate-900 mb-6 leading-tight">
          AI-Powered Document Signing Software
        </h1>
        <p className="text-xl text-slate-600 mb-8">
          traditional e-signature tools charges $45/mo per user. Signova AI starts at $15/mo — with AI document generation, unlimited templates, and a full audit trail included.
        </p>

        {/* Pricing comparison table */}
        <div className="overflow-hidden rounded-2xl border border-slate-200 mb-12">
          <table className="w-full">
            <thead>
              <tr className="bg-slate-50">
                <th className="text-left px-6 py-4 text-slate-700 font-semibold">Feature</th>
                <th className="text-center px-6 py-4 text-slate-500 font-semibold">traditional e-signature tools</th>
                <th className="text-center px-6 py-4 text-indigo-600 font-semibold">Signova AI</th>
              </tr>
            </thead>
            <tbody>
              {[
                { feature: 'Starting price', them: '$45/mo', us: '$15/mo' },
                { feature: 'AI document drafting', them: '✗', us: '✓' },
                { feature: 'Unlimited templates', them: '✗ (add-on)', us: '✓ Included' },
                { feature: 'Audit trail', them: '✓ (paid tier)', us: '✓ All plans' },
                { feature: 'Mobile signing', them: '✓', us: '✓' },
                { feature: 'Bulk sending', them: '✗ (enterprise)', us: '✓ Included' },
                { feature: 'Setup time', them: '2–3 days', us: '< 10 minutes' },
              ].map((row, i) => (
                <tr key={i} className={i % 2 === 0 ? 'bg-white' : 'bg-slate-50'}>
                  <td className="px-6 py-3 text-slate-700">{row.feature}</td>
                  <td className="px-6 py-3 text-center text-slate-500">{row.them}</td>
                  <td className="px-6 py-3 text-center text-indigo-600 font-medium">{row.us}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Lead capture */}
        <div className="bg-indigo-600 rounded-2xl p-8 text-white mb-12">
          <h2 className="text-2xl font-bold mb-2">Switch from traditional e-signature tools in 10 minutes</h2>
          <p className="text-indigo-200 mb-6">We'll import your existing templates for free. No credit card required.</p>
          {!submitted ? (
            <form onSubmit={handleCapture} className="flex gap-3">
              <input
                type="email"
                value={email}
                onChange={e => setEmail(e.target.value)}
                placeholder="your@email.com"
                required
                className="flex-1 px-4 py-3 rounded-lg text-slate-900 text-sm"
              />
              <button type="submit" className="bg-white text-indigo-600 font-semibold px-6 py-3 rounded-lg hover:bg-indigo-50 transition-colors whitespace-nowrap">
                Start Free Trial
              </button>
            </form>
          ) : (
            <p className="text-indigo-100 font-medium">Check your email — your free trial link is on its way.</p>
          )}
        </div>

        <div className="prose prose-slate max-w-none">
          <h2>Why teams switch from traditional e-signature tools to Signova AI</h2>
          <p>traditional e-signature tools was built before AI changed what document software could do. Signova AI was built from the ground up with AI at its core — so instead of just collecting signatures, it helps you draft, send, and manage your entire document workflow automatically.</p>
          <h3>The real cost of traditional e-signature tools</h3>
          <p>At $45/mo per user, a team of 5 pays $225/month or $2,700/year just for e-signatures. Signova AI gives the same team full AI-powered document management for a fraction of that cost — with features traditional e-signature tools charges extra for.</p>
          <h3>Migration takes 10 minutes</h3>
          <p>Upload your existing templates, invite your team, and you're live. Our onboarding team will help you migrate any existing workflows at no cost.</p>
        </div>
      </div>
    </div>
  );
}
