import React, { useState } from 'react';

// SEO: E-Signature Software for Healthcare | Industry: Healthcare
// Generated by Signova Programmatic SEO Engine

export default function HealthcareESignature() {
  const [email, setEmail] = useState('');
  const [submitted, setSubmitted] = useState(false);

  const handleCapture = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await fetch('/api/intent-capture', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, source: 'e-signature-for-healthcare', industry: 'Healthcare' })
      });
    } catch {}
    setSubmitted(true);
  };

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <div className="mb-4 inline-block bg-indigo-50 text-indigo-700 text-sm font-medium px-3 py-1 rounded-full">
          Built for Healthcare
        </div>
        <h1 className="text-4xl font-bold text-slate-900 mb-6 leading-tight">
          E-Signature Software for Healthcare
        </h1>
        <p className="text-xl text-slate-600 mb-8">
          Signova AI helps Healthcare professionals sign patient consent forms, HIPAA authorizations, provider agreements in minutes — with AI that drafts, sends, and tracks every document automatically.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
          {[
            { stat: '4 min', label: 'Average signing time' },
            { stat: '100%', label: 'Legally binding' },
            { stat: '67%', label: 'Less than DocuSign' },
          ].map((item) => (
            <div key={item.label} className="bg-slate-50 rounded-xl p-6 text-center">
              <div className="text-3xl font-bold text-indigo-600 mb-2">{item.stat}</div>
              <div className="text-slate-600 text-sm">{item.label}</div>
            </div>
          ))}
        </div>
        <div className="bg-indigo-600 rounded-2xl p-8 text-white mb-12">
          <h2 className="text-2xl font-bold mb-4">Start signing patient consent forms today</h2>
          {!submitted ? (
            <form onSubmit={handleCapture} className="flex gap-3">
              <input
                type="email"
                value={email}
                onChange={e => setEmail(e.target.value)}
                placeholder="your@email.com"
                required
                className="flex-1 px-4 py-3 rounded-lg text-slate-900 text-sm"
              />
              <button type="submit" className="bg-white text-indigo-600 font-semibold px-6 py-3 rounded-lg hover:bg-indigo-50 transition-colors whitespace-nowrap">
                Get Free Access
              </button>
            </form>
          ) : (
            <p className="text-indigo-100 font-medium">Check your email — your free access link is on its way.</p>
          )}
        </div>
        <div className="prose prose-slate max-w-none">
          <h2>Why Healthcare professionals choose Signova AI</h2>
          <p>Managing patient consent forms, HIPAA authorizations, provider agreements manually costs Healthcare professionals hours every week. Signova AI automates the entire workflow — from document creation to signature collection to secure storage — so you can focus on your clients, not your paperwork.</p>
          <h3>Key features for Healthcare</h3>
          <ul>
            <li>AI-powered document drafting tailored to Healthcare workflows</li>
            <li>Legally binding electronic signatures with full audit trail</li>
            <li>Automatic reminders for unsigned documents</li>
            <li>Secure cloud storage with instant retrieval</li>
            <li>Mobile-friendly signing for clients on any device</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
